/*
 * Built-in palette stops for core/rd.c, generated by scripts/gen-palettes.mjs
 * from lib/palettes.ts, where the colormap sources are recorded. Do not
 * edit. Palette i has PALETTE_STOP_COUNT[i] stops equally spaced from
 * intensity 0 to 1.0, and none for the monochrome threshold palette.
 */
/* clang-format off */
#define PALETTE_BUILTIN_COUNT 9

static const uint8_t PALETTE_STOP_COUNT[PALETTE_BUILTIN_COUNT] = {2, 2, 0, 8, 8, 8, 8, 8, 8};

static const uint8_t PALETTE_STOPS[PALETTE_BUILTIN_COUNT][RD_PALETTE_MAX_STOPS][3] = {
    {{0, 30, 18}, {210, 255, 85}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, /* green */
    {{0, 0, 45}, {85, 255, 255}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, /* blue */
    {{0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, /* mono */
    {{68, 1, 84}, {70, 50, 126}, {54, 92, 141}, {39, 127, 142}, {31, 161, 135}, {74, 193, 109}, {160, 218, 57}, {253, 231, 37}}, /* viridis */
    {{0, 0, 4}, {34, 17, 80}, {95, 24, 127}, {152, 45, 128}, {211, 67, 110}, {248, 118, 92}, {254, 187, 129}, {252, 253, 191}}, /* magma */
    {{13, 8, 135}, {83, 2, 163}, {139, 10, 165}, {184, 50, 137}, {219, 92, 104}, {244, 136, 73}, {254, 189, 42}, {240, 249, 33}}, /* plasma */
    {{0, 0, 4}, {40, 11, 83}, {101, 21, 110}, {159, 42, 99}, {212, 72, 66}, {245, 125, 21}, {250, 194, 40}, {252, 255, 164}}, /* inferno */
    {{0, 34, 78}, {33, 59, 110}, {76, 85, 108}, {108, 110, 114}, {142, 137, 120}, {177, 165, 112}, {217, 197, 92}, {254, 232, 56}}, /* cividis */
    {{48, 18, 59}, {71, 118, 238}, {27, 208, 213}, {97, 252, 108}, {210, 233, 53}, {254, 155, 45}, {218, 57, 7}, {122, 4, 3}}, /* turbo */
};
