import type { Parameters } from "../../lib/simulation.ts";
import { effective } from "../../lib/wasm-simulation.ts";
import { fontIndex, type ClockFont } from "../../lib/clock-fonts.ts";
import { PALETTES, paletteIndex } from "../../lib/palettes.ts";
import {
  engineMode,
  engineWidth,
  gridHeight,
  isFloat,
  HALO,
  type Engine,
} from "../core/modes.ts";

export const DEVICE_MINUTE_STEPS = 300;
export const DEVICE_MINUTE_STEPS_PLAIN = 16;

export type SettingsInput = {
  params: Parameters;
  engine: Engine;
  seed: number;
  palette: string;
  quantize: boolean;
  interpolate: boolean;
  clock: boolean;
  font: ClockFont;
  avoid: boolean;
  steps: number;
};

export function makeSettings(input: SettingsInput) {
  const {
    params,
    engine,
    seed,
    palette,
    quantize,
    interpolate,
    clock,
    font,
    avoid,
    steps,
  } = input;
  const width = engineWidth(engine);
  const floatMode = isFloat(engine);
  return {
    model: "Gray-Scott",
    version: 4,
    method: engine,
    rounding: floatMode
      ? "float32-storage"
      : engine === "u8-200"
        ? "floyd-steinberg-dithered"
        : "floyd-steinberg-nearest",
    storage: floatMode
      ? "float32"
      : engine === "u8-200"
        ? "packed-a7-linear-b9-sqrt"
        : "q15",
    effective: floatMode ? params : effective(params, engineMode(engine)),
    ...params,
    width,
    height: gridHeight(width),
    seed,
    boundary: "periodic",
    laplacian: { center: -1, axial: 0.2, diagonal: 0.05 },
    initialization: "24 display-coordinate disks, radius 4–9, A=0.5 B=0.25",
    palette,
    quantize,
    interpolate,
    clock,
    font,
    avoidDigits: clock && avoid,
    halo: HALO,
    minuteSteps:
      clock && avoid ? DEVICE_MINUTE_STEPS : DEVICE_MINUTE_STEPS_PLAIN,
    steps,
  };
}

/** A pebble/src/c/config.h for this configuration: the build values, and
 * the settings the face shows until the phone sends its own. */
export function makeHeader(input: SettingsInput) {
  if (isFloat(input.engine))
    throw new Error("Float32 cannot produce Pebble config.h");
  const q = effective(input.params);
  const q15 = (value: number) => Math.round(Number(value) * 32768);
  const { engine, seed, palette, interpolate, clock, font, avoid } = input;
  const index = paletteIndex(palette);
  const stops = PALETTES[index].stops.length
    ? PALETTES[index].stops
    : PALETTES[0].stops;
  const hex = (rgb: readonly number[]) =>
    `0x${rgb.map((c) => c.toString(16).padStart(2, "0")).join("")}`;
  return `/* Generated by the Turing Pattern demo, core v4. The RD_DEFAULT_* values
 * are the settings the face shows until the phone sends its own. */
#ifndef RD_MODE
#define RD_MODE ${engineMode(engine)}
#endif
#define RD_SEED ${seed}u
#ifndef RD_RENDER_FLAGS
#define RD_RENDER_FLAGS ${interpolate ? 2 : 0}
#endif
#ifndef RD_LOG
#if defined(RD_PROFILE) || defined(RD_BENCH) || defined(RD_FRAME_BENCH)
#define RD_LOG 1
#else
#define RD_LOG 0
#endif
#endif
#ifndef RD_STARTUP_MS
#define RD_STARTUP_MS 30000
#endif
#define RD_STARTUP_STEPS_MAX 2500
#ifndef RD_AVOID
#define RD_AVOID (RD_MODE != 0)
#endif
#define RD_HALO ${HALO}
#define RD_MINUTE_STEPS_AVOID ${DEVICE_MINUTE_STEPS}
#define RD_MINUTE_STEPS_PLAIN ${DEVICE_MINUTE_STEPS_PLAIN}
#define RD_DEFAULT_FEED ${q15(q.feed)}
#define RD_DEFAULT_KILL ${q15(q.kill)}
#define RD_DEFAULT_DA ${q15(q.da)}
#define RD_DEFAULT_DB ${q15(q.db)}
#define RD_DEFAULT_DT ${q15(q.dt)}
#define RD_DEFAULT_PALETTE ${index}
#define RD_DEFAULT_LOW ${hex(stops[0])}
#define RD_DEFAULT_HIGH ${hex(stops[stops.length - 1])}
#define RD_DEFAULT_FONT ${fontIndex(font)}
#define RD_DEFAULT_AVOID ${Number(avoid)}
#define RD_DEFAULT_CLOCK ${Number(clock)}
`;
}
