import {
  modelIndex,
  parameterOrder,
  parameterValues,
  parameterVector,
  type Parameters,
} from "../../lib/simulation.ts";
import { effective } from "../../lib/wasm-simulation.ts";
import { fontIndex, type ClockFont } from "../../lib/clock-fonts.ts";
import { PALETTES, paletteIndex } from "../../lib/palettes.ts";
import {
  GRID_HEIGHT,
  GRID_WIDTH,
  isFloat,
  HALO,
  SWEEP_MS,
  type ClockFace,
  type Engine,
} from "../core/modes.ts";
import {
  WAVE_END,
  WAVE_EXCITED,
  WAVE_REFRACTORY,
  WAVE_TOP,
} from "../../lib/fhn-simulation.ts";

export const DEVICE_MINUTE_STEPS = 300;

const MODEL_NAMES = {
  "gray-scott": "Gray-Scott",
  fhn: "FitzHugh-Nagumo",
} as const;

/** The initial field of a parameter set, as rd_init_model builds it. */
function initialization(params: Parameters) {
  if (params.model === "gray-scott")
    return "24 display-coordinate disks, radius 4–9, A=0.5 B=0.25 over A=1 B=0";
  const rest = "u=rest, v=rest/av";
  return params.init === 1
    ? `broken wave: u=1 at display rows ${WAVE_TOP}–${WAVE_TOP + WAVE_EXCITED - 1} and v=1 at rows ${WAVE_TOP - WAVE_REFRACTORY}–${WAVE_TOP - 1}, columns 0–${WAVE_END - 1}, over ${rest}`
    : `24 display-coordinate disks, radius 4–9, u=rest+0.5 over ${rest}`;
}
export const DEVICE_MINUTE_STEPS_PLAIN = 16;

export type SettingsInput = {
  params: Parameters;
  engine: Engine;
  seed: number;
  palette: string;
  quantize: boolean;
  interpolate: boolean;
  clock: boolean;
  font: ClockFont;
  face: ClockFace;
  avoid: boolean;
  steps: number;
};

export function makeSettings(input: SettingsInput) {
  const {
    params,
    engine,
    seed,
    palette,
    quantize,
    interpolate,
    clock,
    font,
    face,
    avoid,
    steps,
  } = input;
  const floatMode = isFloat(engine);
  const values = parameterValues(params);
  return {
    model: MODEL_NAMES[params.model],
    version: 5,
    method: engine,
    rounding: floatMode ? "float32-storage" : "floyd-steinberg-nearest",
    storage: floatMode
      ? "float32"
      : params.model === "fhn"
        ? "q15-fraction-(x+2)/4"
        : "q15",
    effective: floatMode ? values : parameterValues(effective(params)),
    ...values,
    width: GRID_WIDTH,
    height: GRID_HEIGHT,
    seed,
    boundary: "periodic",
    laplacian: { center: -1, axial: 0.2, diagonal: 0.05 },
    initialization: initialization(params),
    palette,
    quantize,
    interpolate,
    clock,
    font,
    face,
    avoidDigits: clock && avoid,
    halo: HALO,
    minuteSteps:
      clock && avoid ? DEVICE_MINUTE_STEPS : DEVICE_MINUTE_STEPS_PLAIN,
    steps,
  };
}

/** A pebble/src/c/config.h for this configuration: the build values, and
 * the settings the face shows until the phone sends its own, with the model
 * and its Q15 parameter vector (which the core folds itself). */
export function makeHeader(input: SettingsInput) {
  if (isFloat(input.engine))
    throw new Error("Float32 cannot produce Pebble config.h");
  const { params, seed, palette, interpolate, clock, font, face, avoid } =
    input;
  const vector = parameterVector(params).slice(
    0,
    parameterOrder[params.model].length
  );
  const index = paletteIndex(palette);
  const stops = PALETTES[index].stops.length
    ? PALETTES[index].stops
    : PALETTES[0].stops;
  const [low, high] = [stops[0], stops[stops.length - 1]];
  /** A point between the dark and light stops, for the custom middles. */
  const between = (t: number) =>
    low.map((c, i) => Math.round(c + (high[i] - c) * t));
  const hex = (rgb: readonly number[]) =>
    `0x${rgb.map((c) => c.toString(16).padStart(2, "0")).join("")}`;
  return `/* Generated by the Turing Pattern demo, core v5. The RD_DEFAULT_* values
 * are the settings the face shows until the phone sends its own. */
#define RD_SEED ${seed}u
#ifndef RD_RENDER_FLAGS
#define RD_RENDER_FLAGS ${interpolate ? 2 : 0}
#endif
#ifndef RD_LOG
#if defined(RD_PROFILE) || defined(RD_BENCH) || defined(RD_FRAME_BENCH)
#define RD_LOG 1
#else
#define RD_LOG 0
#endif
#endif
#ifndef RD_STARTUP_MS
#define RD_STARTUP_MS 30000
#endif
#define RD_STARTUP_STEPS_MAX 2500
#define RD_SWEEP_MS ${SWEEP_MS}
#define RD_HALO ${HALO}
#define RD_MINUTE_STEPS_AVOID ${DEVICE_MINUTE_STEPS}
#define RD_MINUTE_STEPS_PLAIN ${DEVICE_MINUTE_STEPS_PLAIN}
#ifndef RD_DEFAULT_MODEL
#define RD_DEFAULT_MODEL ${modelIndex[params.model]}
#endif
#ifndef RD_DEFAULT_PARAMS
#define RD_DEFAULT_PARAMS ${vector.join(", ")}
#endif
#if defined(RD_MODEL) && RD_MODEL != RD_DEFAULT_MODEL
#error "RD_DEFAULT_MODEL must be the model the build is folded to (RD_MODEL)"
#endif
#define RD_DEFAULT_PALETTE ${index}
#define RD_DEFAULT_LOW ${hex(stops[0])}
#define RD_DEFAULT_HIGH ${hex(stops[stops.length - 1])}
#define RD_DEFAULT_STOPS 2
#define RD_DEFAULT_MID1 ${hex(between(1 / 3))}
#define RD_DEFAULT_MID2 ${hex(between(2 / 3))}
#define RD_DEFAULT_FONT ${fontIndex(font)}
#define RD_DEFAULT_AVOID ${Number(avoid)}
#define RD_DEFAULT_CLOCK ${Number(clock)}
#define RD_DEFAULT_DATE 1
#define RD_DEFAULT_FACE ${face === "analog" ? 1 : 0}
`;
}
