import { css } from "../../styled-system/css";

export const styles = {
  page: css({
    maxWidth: "[1160px]",
    mx: "auto",
    px: "30",
    py: "50",
    color: "text",
    background: "background",
  }),
  title: css({ textStyle: "heading/m", mb: "20" }),
  layout: css({
    display: "grid",
    gap: "50",
    lg: { gridTemplateColumns: "minmax(300px,1fr) minmax(340px,440px)" },
  }),
  stage: css({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "20",
    p: "30",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "border.secondary",
    borderRadius: "m",
    background: "background.secondary",
  }),
  canvas: css({
    display: "block",
    width: "[400px]",
    maxWidth: "[100%]",
    aspectRatio: "200 / 228",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "border.secondary",
    cursor: "crosshair",
  }),
  canvasActual: css({ width: "[200px]" }),
  row: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "10",
    alignItems: "center",
  }),
  stack: css({ display: "grid", gap: "20", alignContent: "start" }),
  panel: css({
    display: "grid",
    gap: "20",
    alignContent: "start",
    p: "30",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "border.secondary",
    borderRadius: "m",
    background: "container",
  }),
  heading: css({ textStyle: "heading/xxs", mb: "20" }),
  label: css({ display: "grid", gap: "10", textStyle: "caption/regular/m" }),
  switchLabel: css({
    display: "inline-grid",
    gridTemplateColumns: "auto 1fr",
    gap: "10",
    alignItems: "center",
    fontSize: "[14px]",
    lineHeight: "[22px]",
    cursor: "pointer",
    "&[aria-disabled=true]": {
      opacity: "0.32",
      cursor: "default",
      "& > input": { opacity: "1" },
    },
  }),
  switchInput: css({
    appearance: "none",
    display: "inline-flex",
    position: "relative",
    boxSizing: "border-box",
    width: "[28px]",
    height: "[16px]",
    m: "0",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: "border.transparent",
    borderRadius: "xl",
    backgroundColor: {
      base: "neutral.light.50",
      _dark: "neutral.dark.30",
    },
    cursor: "pointer",
    transition: "[background-color 0.2s, box-shadow 0.2s]",
    _after: {
      content: '""',
      position: "absolute",
      display: "block",
      top: "0",
      left: "0",
      width: "[12px]",
      height: "[12px]",
      transform: "translateX(0)",
      transition: "[transform 0.2s]",
      borderRadius: "full",
      backgroundColor: "text.onPrimary",
    },
    _checked: {
      backgroundColor: "container.primary",
      _after: { transform: "translateX(12px)" },
    },
    _disabled: { opacity: "0.32", cursor: "default" },
    "&:not(:disabled)": {
      _hover: {
        backgroundColor: { base: "neutral.light.60", _dark: "neutral.dark.40" },
      },
      _active: {
        backgroundColor: { base: "neutral.light.70", _dark: "neutral.dark.50" },
      },
      _checked: {
        _hover: { backgroundColor: "container.primary.hover" },
        _active: { backgroundColor: "container.primary.press" },
      },
      _focusVisible: {
        outline: "none",
        boxShadow: "0 0 0 4px rgba(0, 150, 250, 0.32)",
      },
    },
  }),
  field: css({
    minWidth: "[90px]",
    px: "20",
    py: "10",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "border.secondary",
    borderRadius: "m",
    background: "background",
    color: "text",
    _focusVisible: {
      outlineWidth: "2px",
      outlineStyle: "solid",
      outlineColor: "border.focus.2",
    },
  }),
  rangeControl: css({ display: "grid", gap: "25" }),
  rangeTop: css({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "20",
    textStyle: "caption/regular/m",
  }),
  rangeNumber: css({
    flex: "none",
    width: "[90px]",
    textAlign: "right",
    fontVariantNumeric: "tabular-nums",
  }),
  radioGroup: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "30",
    m: "0",
    p: "0",
    border: "none",
  }),
  radioLegend: css({ mb: "10", textStyle: "caption/regular/m" }),
  radioOption: css({
    display: "flex",
    alignItems: "center",
    gap: "20",
    flex: "none",
    width: "[100%]",
    minWidth: "[0]",
    fontSize: "[14px]",
    lineHeight: "[22px]",
    cursor: "pointer",
    "@media (min-width: 480px)": {
      width: "[calc((100% - 16px) / 2)]",
    },
  }),
  radioInput: css({
    appearance: "none",
    display: "block",
    boxSizing: "border-box",
    width: "[20px]",
    height: "[20px]",
    m: "0",
    p: "[6px]",
    borderRadius: "full",
    backgroundColor: "container",
    cursor: "pointer",
    transition: "[background-color 0.2s, box-shadow 0.2s]",
    "&:not(:checked)": {
      borderWidth: "2px",
      borderStyle: "solid",
      borderColor: "border",
    },
    _checked: {
      backgroundColor: "container.primary",
      _after: {
        content: '""',
        display: "block",
        width: "[8px]",
        height: "[8px]",
        borderRadius: "full",
        backgroundColor: "text.onPrimary",
        pointerEvents: "none",
      },
    },
    "&:not(:disabled)": {
      _hover: { backgroundColor: "container.hover" },
      _active: { backgroundColor: "container.press" },
      _checked: {
        _hover: { backgroundColor: "container.primary.hover" },
        _active: { backgroundColor: "container.primary.press" },
      },
      _focusVisible: {
        outline: "none",
        boxShadow: "0 0 0 4px rgba(0, 150, 250, 0.32)",
      },
    },
  }),
  selectWrap: css({ position: "relative", display: "block" }),
  select: css({
    appearance: "none",
    width: "[100%]",
    minHeight: "[40px]",
    pl: "20",
    pr: "40",
    py: "10",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "border.secondary",
    borderRadius: "m",
    background: "background",
    color: "text",
    cursor: "pointer",
    _hover: { background: "container.secondary.hover" },
    _focusVisible: {
      borderColor: "border.focus.1",
      outlineWidth: "2px",
      outlineStyle: "solid",
      outlineColor: "border.focus.2",
    },
  }),
  selectArrow: css({
    position: "absolute",
    top: "[50%]",
    right: "20",
    transform: "translateY(-50%)",
    width: "[16px]",
    height: "[16px]",
    color: "text.secondary",
    pointerEvents: "none",
  }),
  slider: css({
    appearance: "none",
    display: "block",
    width: "[100%]",
    height: "[20px]",
    m: "0",
    backgroundColor: "transparent",
    cursor: "pointer",
    "&::-webkit-slider-runnable-track": {
      height: "[4px]",
      borderRadius: "full",
      backgroundImage:
        "[linear-gradient(to right, var(--colors-container-primary) 0 var(--slider-progress), var(--colors-container-secondary) var(--slider-progress) 100%)]",
    },
    "&::-moz-range-track": {
      height: "[4px]",
      borderRadius: "full",
      backgroundImage:
        "[linear-gradient(to right, var(--colors-container-primary) 0 var(--slider-progress), var(--colors-container-secondary) var(--slider-progress) 100%)]",
    },
    "&::-webkit-slider-thumb": {
      appearance: "none",
      width: "[16px]",
      height: "[16px]",
      mt: "[-6px]",
      borderWidth: "2px",
      borderStyle: "solid",
      borderColor: "container.primary",
      borderRadius: "full",
      background: "container",
    },
    "&::-moz-range-thumb": {
      width: "[16px]",
      height: "[16px]",
      borderWidth: "2px",
      borderStyle: "solid",
      borderColor: "container.primary",
      borderRadius: "full",
      background: "container",
    },
    "&:hover::-webkit-slider-thumb": { borderColor: "container.primary.hover" },
    "&:hover::-moz-range-thumb": { borderColor: "container.primary.hover" },
    "&:focus-visible": {
      outline: "none",
    },
    "&:focus-visible::-webkit-slider-thumb": {
      boxShadow: "0 0 0 4px rgba(0, 150, 250, 0.32)",
    },
    "&:focus-visible::-moz-range-thumb": {
      boxShadow: "0 0 0 4px rgba(0, 150, 250, 0.32)",
    },
  }),
  button: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "[34px]",
    px: "30",
    py: "[5px]",
    borderRadius: "full",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "border.transparent",
    background: "container.secondary",
    color: "text",
    textStyle: "caption/bold/m",
    cursor: "pointer",
    _hover: { background: "container.secondary.hover" },
    _focusVisible: {
      outlineWidth: "2px",
      outlineStyle: "solid",
      outlineColor: "border.focus.2",
    },
    _disabled: { opacity: "0.5", cursor: "not-allowed" },
  }),
  buttonPrimary: css({
    background: "container.primary",
    color: "text.onPrimary",
    _hover: { background: "container.primary.hover" },
  }),
  note: css({ textStyle: "caption/regular/m", color: "text.secondary" }),
  fine: css({ textStyle: "caption/regular/s", color: "text.secondary" }),
  stats: css({ display: "flex", flexWrap: "wrap", gap: "30", py: "30" }),
  stat: css({ display: "grid", gap: "[5px]", textStyle: "caption/regular/s" }),
  statValue: css({ textStyle: "heading/xxs" }),
  section: css({ mt: "50" }),
  details: css({
    mt: "20",
    p: "30",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "border.secondary",
    borderRadius: "m",
  }),
  prose: css({ mt: "20", lineHeight: "1.8", color: "text.secondary" }),
  pre: css({
    overflow: "auto",
    p: "20",
    background: "background.secondary",
    textStyle: "paragraph/code",
  }),
  link: css({
    color: "text.info",
    textDecoration: "underline",
    _hover: { color: "text.info.hover" },
  }),
};
