// Inline the built settings page into one HTML file and write the phone
// script that embeds it. Runs after `vite build --config
// vite.settings.config.ts`, and `pnpm run build:settings` runs both.
//
//   build/config/index.html                     the self-contained page
//   pebble/src/pkjs/generated/pebble-js-app.js  RD_PAGE_HTML, RD_CONFIG_URL,
//                                               RD_PARAM_RANGES, and
//                                               pebble/src/pkjs/index.js
//
// RD_BUILD_CONFIG_URL, when set, is the address of a hosted copy of the
// page that the phone opens instead of the embedded one.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { modelIndex, parameterRanges } from "../lib/presets.ts";

const root = new URL("../", import.meta.url);
const dir = new URL("build/config/", root);
const asset = (path) => readFileSync(new URL(path, dir), "utf8");

let html = asset("index.html")
  .replace(
    /<script type="module" crossorigin src="([^"]+)"><\/script>/g,
    (_, src) =>
      `<script type="module">${asset(src).replaceAll("</script", "<\\/script")}</script>`
  )
  .replace(
    /<link rel="stylesheet" crossorigin href="([^"]+)">/g,
    (_, href) => `<style>${asset(href)}</style>`
  );
if (/\s(src|href)="\.\/assets\//.test(html))
  throw new Error("An asset of the settings page was not inlined");
// The phone replaces the first __SETTINGS__ with the settings, so it must
// be the settings element's placeholder and appear nowhere else.
if (html.split("__SETTINGS__").length !== 2)
  throw new Error("__SETTINGS__ must appear once in the settings page");
writeFileSync(new URL("index.html", dir), html);
rmSync(new URL("assets/", dir), { recursive: true, force: true });

// An ASCII string literal, so the phone reads the script in any encoding.
const literal = (text) =>
  JSON.stringify(text).replace(
    /[\u007f-￿]/g,
    (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`
  );
const pkjs = new URL("pebble/src/pkjs/", root);
// The range of each entry of each model's parameter vector, by model number,
// as the watch and the settings page check them.
const ranges = Object.entries(modelIndex)
  .sort((a, b) => a[1] - b[1])
  .map(([model]) => parameterRanges(model));
const script =
  "// Generated by scripts/embed-config.mjs. Do not edit.\n" +
  `var RD_PAGE_HTML = ${literal(html)};\n` +
  `var RD_CONFIG_URL = ${literal(process.env.RD_BUILD_CONFIG_URL ?? "")};\n` +
  `var RD_PARAM_RANGES = ${JSON.stringify(ranges)};\n` +
  readFileSync(new URL("index.js", pkjs), "utf8");
mkdirSync(new URL("generated/", pkjs), { recursive: true });
writeFileSync(new URL("generated/pebble-js-app.js", pkjs), script);
const url = `data:text/html;charset=utf-8,${encodeURIComponent(html)}`;
console.log(
  `settings page ${html.length} B, data URL ${url.length} B, phone script ${script.length} B`
);
