"""Generate core/clock_trig.h, the sine table of the analog clock face.

Usage: python scripts/gen-clock-trig.py

The angle unit is 1/1440 of a turn (CM_TURN in core/clock_mask.h). The table
holds sin(2 pi k / 1440) in Q14 for the first quadrant, k = 0..360, rounded
to the nearest integer, so that entry 360 is exactly 16384. core/clock_mask.c
folds the other quadrants onto it.
"""

import math
from pathlib import Path

QUADRANT = 360
TURN = 4 * QUADRANT
ONE = 1 << 14
VALUES_PER_LINE = 12

values = [round(math.sin(2 * math.pi * k / TURN) * ONE) for k in range(QUADRANT + 1)]
if values[0] != 0 or values[QUADRANT] != ONE:
    raise SystemExit('the table must run from 0 to exactly 16384')

rows = [values[i : i + VALUES_PER_LINE] for i in range(0, len(values), VALUES_PER_LINE)]
out = [
    '/*',
    ' * Sine table of the analog clock face for core/clock_mask.c, generated by',
    ' * scripts/gen-clock-trig.py. Do not edit.',
    ' *',
    f' * CM_SIN_Q14[k] = round(sin(2 pi k / {TURN}) * {ONE}) for the first quadrant,',
    f' * k = 0..{QUADRANT}.',
    ' */',
    '/* clang-format off */',
    '',
    f'static const int16_t CM_SIN_Q14[{QUADRANT + 1}] = {{',
    *('    ' + ', '.join(str(v) for v in row) + ',' for row in rows),
    '};',
    '',
    '/* clang-format on */',
    '',
]
Path('core/clock_trig.h').write_text('\n'.join(out))
