"""Generate core/clock_glyphs.h from public/fonts/clock-fonts.json.

Usage: python scripts/gen-clock-glyphs.py

Each font keeps the glyphs of one clock line: the digits 0-9 at indices 0-9
and the line separator at index 10. The pixels of every glyph are stored
row by row as a bit stream, least significant bit first.
"""

import json
from pathlib import Path

LINES = {'time': ':', 'date': '.'}
DIGITS = '0123456789'
BYTES_PER_LINE = 12
DISPLAY_HEIGHT = 228

data = json.loads(Path('public/fonts/clock-fonts.json').read_text())
source = data['source']
names = [font_set['name'] for font_set in data['sets']]
if names != ['leco', 'bitham']:
    raise SystemExit(f'sets {names} do not match CM_FONT_* in core/clock_mask.h')


def c_bytes(values):
    rows = [
        values[i : i + BYTES_PER_LINE] for i in range(0, len(values), BYTES_PER_LINE)
    ]
    return '\n'.join(
        '    ' + ', '.join(f'0x{v:02x}' for v in row) + ',' for row in rows
    )


def font_tables(line, name):
    """Glyph and bit tables of the font of one line."""
    glyphs = data['fonts'][name]['glyphs']
    bits = []
    entries = []
    for c in DIGITS + LINES[line]:
        g = glyphs[c]
        entries.append(
            f'    {{{g["width"]}, {g["height"]}, {g["left_offset"]}, '
            f'{g["top_offset"]}, {g["advance"]}, {len(bits)}}}, /* {c} */'
        )
        bits.extend(int(b) for b in g['bits'])
    packed = [
        sum(bits[i + j] << j for j in range(8) if i + j < len(bits))
        for i in range(0, len(bits), 8)
    ]
    return (
        f'static const uint8_t CM_BITS_{name}[{len(packed)}] = {{\n{c_bytes(packed)}\n}};\n'
        f'static const CmGlyph CM_GLYPHS_{name}[CM_GLYPHS] = {{\n'
        + '\n'.join(entries)
        + '\n};\n'
    )


out = [
    '/*',
    ' * Clock glyphs for core/clock_mask.c, generated by',
    ' * scripts/gen-clock-glyphs.py from public/fonts/clock-fonts.json. Do not',
    ' * edit.',
    ' *',
    ' * The glyphs are extracted from the PebbleOS system fonts, licensed under',
    ' * the Apache License 2.0:',
    f' *   {source["repository"]}',
    f' *   revision {source["revision"]}',
]
for name, font in data['fonts'].items():
    out.append(f' *   {source["path"]}/{name}.pbf')
    out.append(f' *     sha256 {font["sha256"]}')


def time_alone_top(font_set):
    """Time line top that centers the ink of the time glyphs on the display."""
    glyphs = data['fonts'][font_set['time']['font']]['glyphs']
    line = [glyphs[c] for c in DIGITS + LINES['time']]
    top = min(g['top_offset'] for g in line)
    bottom = max(g['top_offset'] + g['height'] for g in line)
    return (DISPLAY_HEIGHT - (bottom - top)) // 2 - top


out += [
    ' *',
    ' * A watch build defines RD_FONT and compiles the glyphs of that set only.',
    ' */',
    '/* clang-format off */',
    '',
    '/* System font keys and text boxes of each set, for the watch, and the',
    ' * time line top that centers the time alone on the display. */',
    'static const CmLayout CM_LAYOUTS[CM_FONT_COUNT] = {',
]
for font_set in data['sets']:
    time, date = font_set['time'], font_set['date']
    out.append(
        f'    {{"RESOURCE_ID_{time["font"]}", "RESOURCE_ID_{date["font"]}", '
        f'{time["top"]}, {time["box"]}, {date["top"]}, {date["box"]}, '
        f'{time_alone_top(font_set)}}}, /* {font_set["name"]} */'
    )
out += ['};', '']
lines = []
for index, font_set in enumerate(data['sets']):
    out.append(f'#if !defined(RD_FONT) || RD_FONT == {index}')
    entry = []
    for line in LINES:
        name = font_set[line]['font']
        out.append(font_tables(line, name))
        entry.append(f'{{CM_GLYPHS_{name}, CM_BITS_{name}}}')
    out += ['#endif', '']
    lines.append((index, font_set['name'], entry))
out.append(
    '/* Time and date fonts of each set, or NULL when the set is not compiled. */'
)
out.append('static const CmFont CM_FONTS[CM_FONT_COUNT][2] = {')
for index, name, entry in lines:
    out += [
        f'#if !defined(RD_FONT) || RD_FONT == {index}',
        f'    {{{entry[0]}, {entry[1]}}}, /* {name} */',
        '#else',
        '    {{NULL, NULL}, {NULL, NULL}},',
        '#endif',
    ]
out += ['};', '', '/* clang-format on */', '']
Path('core/clock_glyphs.h').write_text('\n'.join(out))
